### PR TITLE
reorganised form

### PR DESCRIPTION
**Pull request by JamesButlerGDS**

### CODE REVIEW

**Comment by fofr** [comment]
Hi @JamesButlerGDS, could you add some more context to this PR?

* What has been reorganised?
* Why has it been reorganised?
* Links to any Trello user stories

**Comment by JamesButlerGDS** [comment]
Hi Paul,

I've created a new step, and placed some of the fields from step 4 into step 5. I've also relabelled some of the fields.

I'd made no notes for the PR as I'd intended it only to be able to provide a preview to a dept, which @ikennaokpala kindly helped me with. I'm going to ensure the work done hasn't caused any issues, and once I've confirmed that, I may reiterate (most likely just tinkering with the labels) then make a proper PR.

Please do let me know if there's a better way to create a workable preview for the calculator, without having to make a PR. 

Thanks,
James

**Comment by fofr** [comment]
@JamesButlerGDS A branch can be deployed to an environment (eg temporarily to Integration) without the need to create a PR.

A PR that is not going to be merged should say why.

If a PR is necessary, a good example title would be:
"[Do not merge] Prototype of re-arranged form for demo purposes"

Though the PR should still include what the prototype is for.

**Comment by ikennaokpala** [comment]
@fofr I advised @JamesButlerGDS to raise that PR to trigger the heroku push feature.. which at the time I thought had been added to this repo.

**Comment by JamesButlerGDS** [comment]
I'll close this request now and work on a new one with what should be the final content iteration.

**Pull request closed without merging**
