### PR TITLE
Routine maintenance upgrades

### PR DESCRIPTION
**Pull request by h-lame**
Our goal is latest rails, ruby 2.3 and adding govuk-lint to the project.  Along the way we also bump some other gems.

Note that this introduces a warning to the test suite about rest-client (see: 5a44e95922a9b0ff95d124cdbc52e130b1e594e5) for details.

For: https://trello.com/c/CYlKdEPi/350-upgrade-calculators-2

### CODE REVIEW

**Comment by chrisroos** [comment]
We encountered this same rest-client warning when upgrading Smart Answers to Ruby 2.3, but decided that we're happy to ignore it for now - https://github.com/alphagov/smart-answers/pull/2345.

**Comment by davidbasalla** [comment]
Not sure if relevant, but the calendars app was also getting loads of SASS linting errors. I fixed the trivial style violations, but after chatting to @dsingleton chose to turn off the linter for the more complex cases, as it seemed that the app's frontend code needed a general overhaul (it hadn't been touched since 2013). The same might apply here.

https://github.com/alphagov/calendars/pull/112/commits/6ae355e584d13834acb0ae5823b8df7cb0e97794

**Comment by h-lame** [comment]
The bits I didn't do (sass, etc) seem good :+1:, thanks @sihugh for finishing this off!

**Comment by davidbasalla** [comment]
This all looks good to me :+1: Merging!

**Pull request merged**
