### PR TITLE
Remove start page from Calculators

### PR DESCRIPTION
**Pull request by fofr**
Depends on #187 and https://github.com/alphagov/publisher/pull/629 tasks being run

Now Publisher and Frontend handle the start page for child benefit tax calculator (it's now a transaction), remove all traces of it.

* Remove template, tests and routes
* Remove old redirects from 2013
* Stop sending anything to search (only the start page should be in search, like other _services_)
* Only publish a content item for the calculator form
* Request the calculator form content item (eg `/main`) (this changes the breadcrumb to the one defined on that content item, currently empty – as discussed with @carvil)

### CODE REVIEW

**Comment by fofr** [comment]
@ikennaokpala All the rummage code has been deleted, so the deploy task is trying to run a rake task that no longer exists.

**Comment by ikennaokpala** [comment]
Ahh right!! How can this be skipped.

**Comment by fofr** [comment]
It needs to be removed from here: https://github.com/alphagov/govuk-app-deployment/blob/master/calculators/config/deploy.rb#L16

**Comment by ikennaokpala** [comment]
@fofr I have raised [this PR](https://github.com/alphagov/govuk-app-deployment/pull/155)

**Pull request merged**
