### PR TITLE
Add bearer_token for publishing API authentication

### PR DESCRIPTION
**Pull request by danielroseman**

### CODE REVIEW

**Comment by issyl0** [comment]
This might be something I should already know, but why?

**Comment by issyl0** [comment]
We've got a story for the failing test now: https://trello.com/c/Mux2Mkbv/251-a-test-in-the-calculators-app-is-broken. It's nothing to do with what Daniel's done. :-)

**Comment by elliotcm** [comment]
Build failéd.

**Comment by issyl0** [comment]
The failing test was fixed (removed) in #128, so merging this. :-)

**Pull request merged**
